### ISSUE TITLE
`gaston build` fails on vigour-example, which depends on scratch via uikit

### ISSUE THREAD

**Issue by shawninder** [vigour-io/scratch#6]
```
ERR! gaston Error: Cannot find module 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,200,600,700,900' from '/Users/shawn/Work/vigour-example/node_modules/vigour-scratch/lib/helpers'
ERR! gaston     at /Users/shawn/npmGlobal/lib/node_modules/gaston/node_modules/resolve/lib/async.js:46:17
ERR! gaston     at process (/Users/shawn/npmGlobal/lib/node_modules/gaston/node_modules/resolve/lib/async.js:173:43)
ERR! gaston     at ondir (/Users/shawn/npmGlobal/lib/node_modules/gaston/node_modules/resolve/lib/async.js:188:17)
ERR! gaston     at load (/Users/shawn/npmGlobal/lib/node_modules/gaston/node_modules/resolve/lib/async.js:69:43)
ERR! gaston     at onex (/Users/shawn/npmGlobal/lib/node_modules/gaston/node_modules/resolve/lib/async.js:92:31)
ERR! gaston     at /Users/shawn/npmGlobal/lib/node_modules/gaston/node_modules/resolve/lib/async.js:22:47
ERR! gaston     at FSReqWrap.oncomplete (fs.js:82:15)
ERR! gaston  { [Error: Cannot find module 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,200,600,700,900' from '/Users/shawn/Work/vigour-example/node_modules/vigour-scratch/lib/helpers']
```

Repro:
- `git clone git@github.com:vigour-io/vigour-example.git`
- `cd vigour-example`
- `npm install`
- `npm run build`

**Comment by shawninder** [comment]
I see there is already an issue for this in gaston: https://github.com/vigour-io/gaston/issues/91

**Comment by nikoloza** [comment]
@shawninder Please make sure you have the latest version of Gaston

**Comment by shawninder** [comment]
@nikoloza Aha, I am not any more. Is this new version supposed to fix this issue? Also, aren't you sleeping?

**Comment by shawninder** [comment]
OK, tried it again with gaston v0.25.2. Now I get a different error:

```
node-pre-gyp ERR! gaston { [Error: Operation on an invalid type]
node-pre-gyp ERR! gaston   type: 'Operation',
node-pre-gyp ERR! gaston   filename: 'input',
node-pre-gyp ERR! gaston   index: 83358,
node-pre-gyp ERR! gaston   line: 4724,
node-pre-gyp ERR! gaston   callLine: NaN,
node-pre-gyp ERR! gaston   callExtract: undefined,
node-pre-gyp ERR! gaston   column: 0,
node-pre-gyp ERR! gaston   extract:
node-pre-gyp ERR! gaston    [ '@header-fixed: false;',
node-pre-gyp ERR! gaston      '@header-height: @input-height + 2rem; // if \'@header-fixed\' is true',
node-pre-gyp ERR! gaston      '' ],
node-pre-gyp ERR! gaston   message: 'Operation on an invalid type',
node-pre-gyp ERR! gaston   stack: undefined }
```

**Comment by nikoloza** [comment]
@shawninder yeah, Andre just fixed it today :) Couldn't sleep, got sick and can't breath well :)))

**Comment by shawninder** [comment]
ugh :( Put some ginger and lemon in half a cup of hot water with honey. Then fill the rest of the cup with spiced rum. You'll be feeling better in no time :)

**Comment by nikoloza** [comment]
Thanks man, I'll try this. I'm gonna update `scratch` on npm and please update it on your local machine, let me know if it still breaks. But in `uikit` I did some breaking changes. let me bring them back and pull it again.

**Comment by nikoloza** [comment]
@shawninder I think updating node modules will help now.

**Comment by shawninder** [comment]
Indeed it does! `gaston build` now works for vigour-example
